// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in todo/ent/runtime.go

const (
	Version = "v0.11.3-0.20220907191106-dc44b9f6febc"           // Version of ent codegen.
	Sum     = "h1:pWmWup+I8cjp+6Bz86rWWiSLk6jd0XqCHAC1ypj+6Bo=" // Sum of ent codegen.
)
